spring:
  application:
    name: billing
  profiles:
    active: dev
  cloud:
    discovery:
      client:        health-indicator:          enabled: true

server:
  port: 8080
  context-path: /
  tomcat:
    max-threads: 1000

eureka:
  client:
    service-url:
      defaultZone: http://hien-eureka:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    appname: billing
    non-secure-port: 8080
    health-check-url-path: /health
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    
kafka:
  appId: billing
  endpoint: hien-kafka:9092
  sendSmsTopic: billing-sendSmsTopic

db:
  main:
    host: localhost
    username: root
    password: root
    name: billing
    pool: 2