spring:
  application:
    name: eshopping
  profiles:
    active: dev
  cloud:
    discovery:
      client:
        health-indicator:
          enabled: true

server:
  port: 8080
  context-path: /
  tomcat:
    max-threads: 1000

eureka:
  client:
    serviceUrl:
      defaultZone: http://hien-eureka:8761/eureka/
  instance:
    appname: eshopping
    nonSecurePort: 8080
      
kafka:
  appId: eshopping
  endpoint: hien-kafka:9092
  sendSmsTopic: eshopping-sendSmsTopic
  
db:
  main:
    host: localhost
    username: root
    password: root
    name: eshopping
    pool: 2